USE [GestionMatos]
GO

INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Appareil informatique‎', 1462)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Baladeur numérique‎', 108)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Bus informatique', 3166)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Carte d''extension', 2081)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Carte mère‎', 957)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Connectique‎', 484)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Constructeur informatique‎', 1285)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Lisp‎', 4878)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Matériel de jeu vidéo‎', 3619)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Matériel de réseau informatique', 4170)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Matériel de sécurité informatique‎', 2658)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Matériel informatique libre‎', 2182)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Matériel informatique par entreprise‎', 623)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Mémoire informatique‎', 3564)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Périphérique (informatique)', 694)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Personnalisation du matériel informatique', 3786)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Processeur‎', 1608)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Refroidissement du matériel informatique‎', 2833)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Stockage informatique', 411)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Terminal informatique‎', 153)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Accélération matérielle', 2247)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Advance''Configuration an''Power Interface', 2865)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Alimentation électrique par câble Ethernet', 4795)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('ALPM', 4540)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('AN/FSQ-32', 2315)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Anneau de protection', 2390)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Asynchronisme', 2194)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Audio Codec 97', 880)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Baie (centre de données)', 2225)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Banana Pi', 3851)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Barebone', 1484)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Barebook', 4797)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Baybus', 3496)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Bloc d''alimentation', 125)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Bull Novascale', 4212)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Calculateur stochastique', 2560)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Carte à coprocesseur', 1132)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Carte ARM', 696)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Carte mère', 447)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Centrino', 358)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Chip select', 3366)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Clone (matériel informatique)', 3353)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Codelet', 2540)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Commutateur écran-clavier-souris', 3710)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Compatibilité ascendante et descendante', 1753)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Composition informatique', 25)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Vis pour boîtier de PC', 3537)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Console système', 4368)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Coprocesseur sql', 2068)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Couche d''abstraction matérielle', 2842)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Courbe force course', 4432)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Cubox', 4557)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Dell PowerEdge', 3986)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Dreambox', 4010)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Dynamic Device Mapping', 2017)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Écran ''ordinateur', 887)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Émetteur-récepteur', 10)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Entrées-sorties', 604)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Équipement terminal de circuit de données', 1504)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Expandeur', 2796)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Fab12', 1615)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Fabricant ''équipement ''origine', 2857)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Filtre de confidentialité', 683)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Firmware', 2844)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Fon''de panier', 3079)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('General MIDI', 2064)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('General Purpose Input/Output', 4793)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('GRAIL (informatique)', 3732)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Hardware Compatibility List', 966)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Hot-Plug', 1660)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Hub Ethernet', 3858)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('IBM 4250 (électrocomposeuse)', 4358)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Interruption matérielle', 4734)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('ISCSI', 2602)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Lecteur de CD-ROM', 1689)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Lecteur de Laserdisc', 4785)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Lemur Input Device', 1433)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Librairie de sauvegarde', 1626)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Liste ''ordinateurs du passé par constructeur', 3267)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Liste des ordinateurs à tubes à vide', 2437)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Listing', 4967)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Loi de Moore', 3473)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Micro-casque', 4747)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Mini-ordinateur', 4383)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Multiprocesseur', 2881)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Musical Instrument Digital Interface', 690)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Nano-informatique', 2777)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Network on Chip', 3054)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ordinateur', 1147)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ordinateur à programme enregistré', 2095)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ordinateur à carte unique', 2367)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ordinateur renforcé', 220)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Panneau frontal', 4922)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('PC speaker', 3489)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('PC-on-a-stick', 23)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Performances (informatique)', 1596)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Périphérique informatique', 733)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Personal Internet Communicator', 1724)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('PHY', 1356)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('PICA200', 1893)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('PirateBox', 3070)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Pixar Image Computer', 717)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Plug and Play', 4902)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Plug computer', 2686)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Port matériel', 860)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Port parallèle', 491)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ressource (informatique)', 1357)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Rue Montgallet', 2916)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Serveur vidéo', 1765)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Softmod', 2859)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Sun Ray', 4947)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Synchronisme', 4387)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Tandem Computers', 4811)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Testeur de carte mère', 4823)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Tête de lecture à technologie GMR', 1163)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Tête inductive', 2103)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Tête MR', 4277)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('TiVo', 3296)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Tolérance aux pannes', 2567)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Tour (informatique)', 1770)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ultra-ATA', 351)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Unité centrale', 2235)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Veille (mode de fonctionnement)', 1896)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Ventilateur ''ordinateur', 4333)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Very long instruction word', 4485)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('Video In Video Out', 782)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('WHQL', 4175)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('XS (EVS)', 4867)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('XT(2)+', 3500)
INSERT INTO [dbo].[Type_Materiel] ([nom_Type_Materiel],[MTBF])VALUES ('XT3', 2069)

INSERT [dbo].[Client] ([nom_Client]) VALUES (N'Client de test 1')
INSERT [dbo].[Client] ([nom_Client]) VALUES (N'Client de test 2')
INSERT [dbo].[Client] ([nom_Client]) VALUES (N'Client de test 3')
INSERT [dbo].[Client] ([nom_Client]) VALUES (N'Client de test 4')
INSERT [dbo].[Client] ([nom_Client]) VALUES (N'Client de test 5')

INSERT [dbo].[Site] ([nom_Site], [Adresse]) VALUES (N'Site de stockage 1', N'Adresse de stockage 1')
INSERT [dbo].[Site] ([nom_Site], [Adresse]) VALUES (N'Site de stockage 2', N'Adresse de stockage 2')
INSERT [dbo].[Site] ([nom_Site], [Adresse]) VALUES (N'Site de stockage 3', N'Adresse de stockage 3')

INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (10, 1, 2)
INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (11, 1, 1)
INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (72, 2, 2)
INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (82, 2, 3)
INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (101, 2, 1)
INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (125, 3, 1)
INSERT [dbo].[Batiment] ([num_Batiment], [id_Site], [id_Client]) VALUES (72, 3, 2)

INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 1)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (2, 1)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (3, 1)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (4, 1)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 2)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (2, 2)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (3, 2)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (4, 2)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (5, 2)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (6, 2)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 3)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (2, 3)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (3, 3)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (4, 3)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 4)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (2, 4)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (3, 4)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 5)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (2, 5)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (3, 5)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 6)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (2, 6)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (3, 6)
INSERT [dbo].[Etage] ([num_Etage], [id_Batiment]) VALUES (1, 7)

INSERT [dbo].[Materiel] ([guid_Materiel], [id_type_Materiel], [id_Client], [id_Etage], [date_dernier_Intervention]) VALUES (N'cdc2e8f2-d47f-40d5-b53d-40afa25172c5', 1, 1, 1, CAST(0xBC3A0B00 AS Date))
INSERT [dbo].[Materiel] ([guid_Materiel], [id_type_Materiel], [id_Client], [id_Etage], [date_dernier_Intervention]) VALUES (N'd6c03407-964e-475c-9d18-2fabcf472612', 10, 2, 1, CAST(0xBC3A0B00 AS Date))
INSERT [dbo].[Materiel] ([guid_Materiel], [id_type_Materiel], [id_Client], [id_Etage], [date_dernier_Intervention]) VALUES (N'd6c03407-964e-475c-9d18-2fabcf472612', 10, 3, 1, CAST(0x013A0B00 AS Date))
INSERT [dbo].[Materiel] ([guid_Materiel], [id_type_Materiel], [id_Client], [id_Etage], [date_dernier_Intervention]) VALUES (N'd6c03407-964e-475c-9d18-2fabcf472612', 10, 2, 1, CAST(0x8E390B00 AS Date))

INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle A1', 1)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle A2', 1)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle B1', 2)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle B2', 3)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle B3', 3)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle C1', 4)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle C2', 5)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle C3', 5)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle D1', 6)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle D2', 7)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle E1', 8)
INSERT [dbo].[Salle] ([nom_Salle], [id_Etage]) VALUES (N'Salle E6', 23)